name: Test

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

jobs:
  test-ubuntu:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22.5'

    - name: Get dependencies
      run: go get .

    - name: Build
      run: go build .

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: debug-ubuntu
        path: ${{ github.workspace }}/idFileDeCompressorGo

  test-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22.5'

    - name: Get dependencies
      run: go get .

    - name: Build
      run: go build .

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: debug-windows
        path: ${{ github.workspace }}/idFileDeCompressorGo.exe
